# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('web/dist', 'web/dist'),
        ('web/index.html', 'web'),
        ('config.toml', '.'),
        ('config.toml.example', '.'),
    ],
    hiddenimports=[
        'sqlite3',
        'requests',
        'bs4',
        'feedparser',
        'tomllib',
        'tomli',
        'tomli_w',
        'utils.logger',
        'utils.helpers',
        'utils.progress',
        'utils.image_processor',
        'database.manager',
        'scheduler.scheduler',
        'web.server',
        'fetcher.rss_fetcher',
        'fetcher.api_fetcher',
        'fetcher.web_fetcher',
        'ai.processor',
        'ai.classifier',
        'ai.summarizer',
        'rag.engine',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='kwafoo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)