# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('web/dist', 'web/dist'),
        ('config.toml', '.'),
        ('config.toml.example', '.'),
        ('D:/Python/Lib/site-packages/litellm/model_prices_and_context_window_backup.json', 'litellm'),
    ],
    hiddenimports=[
        'sqlite3',
        'requests',
        'bs4',
        'feedparser',
        'tomllib',
        'tomli',
        'tomli_w',
        'utils.logger',
        'utils.helpers',
        'utils.progress',
        'utils.image_processor',
        'database.manager',
        'scheduler.scheduler',
        'web.server',
        'fetcher.rss_fetcher',
        'fetcher.api_fetcher',
        'fetcher.web_fetcher',
        'ai.processor',
        'ai.classifier',
        'ai.summarizer',
        'rag.engine',
        'litellm',
        'litellm.utils',
        'litellm.integrations',
        'litellm.integrations.custom_logger',
        'tiktoken',
        'tiktoken_ext',
        'tiktoken_ext.openai_public',
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=['hooks/rthook-litellm.py'],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='kwafoo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)