[mypy]
python_version = 3.8
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_unreachable = True
strict_optional = True

[pydantic]
init_forbid_extra = True
init_typed = True
required_fields = True

[mypy-tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-web.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-ai.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-scheduler.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-database.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-fetcher.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-rag.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-utils.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False